default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: 5432

development:
  <<: *default
  database: skpweb_development
  username: postgres
  password: 123456789
  host: localhost

production:
  <<: *default
  database: skpweb_production
  username: postgres
  password: 123456789
  host: localhost
