default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: 5432

development:
  <<: *default
  database: skpweb_development
  localhost: 'localhost'
  username: 'postgres'
  password: 123456789

production:
  <<: *default
  database: skpweb_production
